---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpledb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: simpledb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: simpledb
          image: simpledbregistry.azurecr.io/simpledb-mongo:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://cosmos-13767:ddvs7UdXE8Nh7hWb7e44W1Qp21fzA05K5g7zHUsyMxTEVhaxRMIodmh3aIy8DkG7CQ0GDMCHdkG1Gp3Otm5jIA==@cosmos-13767.mongo.cosmos.azure.com:10255/database1?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmos-13767@"
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: simpledb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simpledb


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simpledb-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpledb
  targetCPUUtilizationPercentage: 50 # target CPU utilization