---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpledb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simpledb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: simpledb
          image: simpledbregistry.azurecr.io/simpledb:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://simpledbpostgres.postgres.database.azure.com:5432/postgres?user=postgresadmin&password=postgresadmin&sslmode=require"
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: simpledb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simpledb


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simpledb-hpa
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpledb
  targetCPUUtilizationPercentage: 50 # target CPU utilization