version: '2'

services:
  app:
    image: 'simpledb'
    build:
      context: .
    container_name: simpledb
    depends_on:
      - mongo
      - cache
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongo:27017/admin
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password

  mongo:
    image: mongo
    ports:
      - 27017:27017

  cache:
    image: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379