version: '2'

services:
  app:
    image: 'simpledb'
    build:
      context: .
    container_name: simpledb
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?user=postgresadmin&password=postgresadmin&sslmode=prefer
    ports:
      - 8080:8080

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=postgresadmin