version: '2'

services:
  app:
    image: 'simpledb'
    build:
      context: .
    container_name: simpledb
    depends_on:
      - mongo
    environment:
      - AUTH_DB=admin
      - USERNAME=admin
      - PASSWORD=secret
      - DB=admin
      - HOST=localhost
      - PORT=27017
    ports:
      - 8080:8080

  mongo:
    image: mongo
    ports:
      - 20717:20717
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret